### PR TITLE
DFL-3538 Change pretty-printing icon

### PR DESCRIPTION
**Pull request by chriskr**

### CODE REVIEW

**Comment by hzr** [comment]
Nice.

**Comment by p01** [comment]
Would be even nicer if the lines had different length.
But it's already one notch better than the current icon.

**Comment by chriskr** [comment]
We have tried different line lengths (and a lot of other things too), it actually doesn't look better.

**Comment by danfooo** [comment]
I see an airplane. Maybe because I am on an airplane.

No, seriously, I don't like all our line-y icons. The views are lines of source already, repeating that in every icon doesn't make sense. It has no visual hold, nothing to get used to or remember.

This is okay since it fits our current icon style, but it's not good.

**Pull request merged**
