### PR TITLE
Fix for DFL-3706, Exception in window.templates.resource_tree._get_short_distinguisher

### PR DESCRIPTION
**Pull request by p01**

### CODE REVIEW

**Comment by danfooo** [comment]
Have you checked how a resource can not have a url? We should normally instantiate a new resource on urlload, that should have the URL already.

**Comment by p01** [comment]
That's right. I have not seen instances of ResourceInfo without a URL.
OTOH the ListDocuments command of the document-manager has returned documents without a URL.

**Comment by danfooo** [comment]
Is it not the resources that get mocked in resource_service.js:479?

**Comment by p01** [comment]
The `url` and `callback` of cls.ResourceRequest are not optional.
cls.ResourceRequest requests the resource for a given url and calls the callback when the payload comes back.

Also, checking the callstack in DFL-3706, shows it threw when called from window.templates.resource_tree.document(...)

**Comment by danfooo** [comment]
Okay, I see. Looks fine then.

**Pull request merged**
