### PR TITLE
Task dfl 2491 resource inspector improvements

### PR DESCRIPTION
**Pull request by p01**
Includes the task_DFL_2973_Make_Request branch.

### CODE REVIEW

**Comment by danfooo** [comment]
Wow, it's big! Does the reviewed branch have everything from task_DFL_2973_Make_Request_reviewed?

**Comment by p01** [comment]
:p I had forgotten to merge task_DFL_2973_Make_Request_reviewed into both branches

**Comment by danfooo** [comment]
You can do that and push both, it updates.

**Comment by p01** [comment]
For posterity: All three branches were not in sync with master, which broke the FastForward-ability of this PR. All is good and well now. See PR #110

**Pull request closed without merging**
