### PR TITLE
Chrisk bugfixes

### PR DESCRIPTION
**Pull request by chriskr**
Two more fixes.

### CODE REVIEW

**Comment by hzr** [comment]
Looks great!

**Comment by danfooo** [comment]
Looks fine

**Comment by chriskr** [comment]
Switched to indexOf instead of RegExp.

**Comment by chriskr** [comment]
Doesn't work properly, something is wrong.

**Comment by chriskr** [comment]
Now it's OK.

**Comment by hzr** [comment]
Looks good!

**Comment by p01** [comment]
Goody

**Pull request merged**
