### PR TITLE
Updated message definitions and made them collapsible.

### PR DESCRIPTION
**Pull request by chriskr**

### CODE REVIEW

**Comment by danfooo** [comment]
Hard to see here, what changed about the defs? Made a diff for src/ui-style/ and src/lib/: http://pastebin.com/Qcf5B9TD

**Comment by chriskr** [comment]
The defs are recreated with the updated tool. Has fixed some formatting issues and added the missing ones mainly. The other change is only in debug mode. Makes it possible to collapse the message definitions in the Test Message view.

**Comment by danfooo** [comment]
Okay, good. Looks fine.

**Comment by hzr** [comment]
Yup.

**Pull request merged**
